#-----------------------------------------------------------------
#Parametros colisao em 3d:                                                   |
#-----------------------------------------------------------------
model: "3D"
a : 30 #Angulo considerado como limite para colisao              |
d_min : 0.55 #distancia minima de colisao                        |
d_max : 0.90 #distancia max de colisao                           |     
#                                                                |
#                                                                |
#-----------------------------------------------------------------
#-----------------------------------------------------------------
#Parametros colisao em 2d:                                                   |
#-----------------------------------------------------------------
#model: "2D"
#d_min : 0.03 #distancia minima de colisao                        |
#d_max : 1.0 #distancia max de colisao                           |     
#                                                                |
#                                                                |
#-----------------------------------------------------------------
